version: '3.8'
services:
  backend:
    build: ./
    ports:
      - '3001:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: example
      DATABASE_NAME: webservice
      JWT_SECRET: secret
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: webservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'